<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>fileflow</ToolCommandName>
    <PackageId>FileFlow.Cli</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RootNamespace>FileFlow.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FileFlow.Core/FileFlow.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
